sudo: false

jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two
    - stage: conditional deploy
      script: echo "Deploying!"
      after_script: echo "Deployed!"
      deploy:
        on:
          condition: $TRAVIS_BRANCH =~ master|production
