sudo: false

jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two
    - stage: conditional deploy
      after_script: echo "Deployed!"
      deploy:
        provider: script
        script: scripts/deploy.sh
        on:
          condition: $TRAVIS_BRANCH =~ master|production
