sudo: false

jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two  
    - stage: runs on foobar branch
      script: echo 'only runs on foobar branch'
      branch: 'foobar'
